package org.apache.jsp.aml;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sinosoft.lis.pubfun.GlobalInput;
import com.sinosoft.lis.pubfun.*;
import com.sinosoft.lis.pubfun.*;

public final class LXISTradeManualDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/aml/../common/jsp/UsrCheck.jsp");
    _jspx_dependants.add("/aml/LXISTradeManualDetailInit.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("<!--\r\n");
      out.write("*******************************************************\r\n");
      out.write("* ³ÌÐòÃû³Æ£ºUsrCheck.jsp\r\n");
      out.write("* ³ÌÐò¹¦ÄÜ£ºÓÃ»§ÐÅÏ¢Ð£ÑéÒ³Ãæ\r\n");
      out.write("* ´´½¨ÈÕÆÚ£º2002-11-25\r\n");
      out.write("* ¸üÐÂ¼ÇÂ¼£º  ¸üÐÂÈË    ¸üÐÂÈÕÆÚ     ¸üÐÂÔ­Òò/ÄÚÈÝ\r\n");
      out.write("*******************************************************\r\n");
      out.write("-->\r\n");
      out.write("\r\n");

try
{
	if (session == null) {
		System.out.println("session is null");

      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("try\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("catch (exception)\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");

		return;
	}
	GlobalInput tG1 = (GlobalInput)session.getValue("GI");
	if (tG1 == null) {
		session.putValue("GI",null);
		out.println("ÍøÒ³³¬Ê±£¬ÇëÄúÖØÐÂµÇÂ¼");

      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("try\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("catch (exception)\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");

		return;
	}
	String  userCode = tG1.Operator;
	String comCode =tG1.ComCode;
	String manageCom = tG1.ManageCom;
	if ((userCode.length()==0) || (userCode.compareTo("")==0)||(comCode.length()==0) || (comCode.compareTo("")==0) ||(manageCom.length()==0) || (manageCom.compareTo("") == 0))
	{
		session.putValue("GI",null);
		String ContentErr = " ÇëÄúÖØÐÂµÇÂ¼£¡";
		System.out.println(ContentErr);

      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("try\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("catch (exception)\r\n");
      out.write("{\r\n");
      out.write("\ttop.window.location =\"../indexlis.jsp\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");

		return;
	}
}
catch(Exception exception)
{
	String ContentErr = " exception:ÇëÄúÖØÐÂµÇÂ¼£¡";
	System.out.println(ContentErr);
	out.println("ÍøÒ³³¬Ê±£¬ÇëÄúÖØÐÂµÇÂ¼");

      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("top.window.location =\"../indexlis.jsp\";\r\n");
      out.write("</script>\r\n");

	return;
}

      out.write("\n");
      out.write("<html>\n");

//程序名称：
//程序功能：
//创建日期：2002-08-21 09:25:18
//创建人 ：HX
//更新记录： 更新人  更新日期   更新原因/内容

      out.write('\n');
      out.write('\n');

	GlobalInput tGI = new GlobalInput();
	tGI = (GlobalInput) session.getValue("GI");

      out.write("\n");
      out.write("<script>\n");
      out.write("  var operator = \"");
      out.print(tGI.Operator);
      out.write("\";   //记录操作员\n");
      out.write("  var manageCom = \"");
      out.print(tGI.ManageCom);
      out.write("\"; //记录管理机构\n");
      out.write("  var comcode = \"");
      out.print(tGI.ComCode);
      out.write("\";     //记录登陆机构\n");
      out.write("</script>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GBK\" />\n");
      out.write("<SCRIPT src=\"../common/javascript/Common.js\" ></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/javascript/MulLine.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/cvar/CCodeOperate.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/Calendar/Calendar.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/javascript/VerifyInput.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/easyQueryVer3/EasyQueryVer3.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"../common/easyQueryVer3/EasyQueryCache.js\"></SCRIPT>\n");
      out.write("<SCRIPT src=\"LXISTradeManualDetailInput.js\"></SCRIPT>\n");
      out.write("<LINK href=\"../common/css/Project.css\" rel=stylesheet type=text/css>\n");
      out.write("<LINK href=\"../common/css/mulLine.css\" rel=stylesheet type=text/css>\n");
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

//程序名称：OrphanPolOutInit.jsp
//程序功能：
//创建日期：2005-05-26 15:39:06
//创建人  ：CrtHtml程序创建
//更新记录：  更新人    更新日期     更新原因/内容

      out.write("\r\n");
      out.write("<!--用户校验类-->\r\n");
      out.write("<SCRIPT src=\"../common/javascript/Common.js\"></SCRIPT>\r\n");

	//添加页面控件的初始化。
	String tDealNo = "";
	tDealNo = request.getParameter("DealNo");
	if (tDealNo==null||tDealNo=="" || "undefined".equals(tDealNo))
  		tDealNo = PubFun1.CreateMaxNo("AMLDEALNO", 20);
	else 
  		tDealNo = new String(request.getParameter("DealNo"));

	String tDataState = "";
	tDataState = request.getParameter("DataState");
	if (tDataState==null||tDataState=="" || "undefined".equals(tDataState))
  		tDataState = "";
	else 
  		tDataState = new String(request.getParameter("DataState"));

	String toper = "";
	toper = request.getParameter("oper");
	if (toper==null||toper=="" || "undefined".equals(toper))
  		toper = "query";
	else 
  		toper = new String(request.getParameter("oper"));
  	
    String currentDate = PubFun.getCurrentDate();
    String currentTime = PubFun.getCurrentTime();  
    
    GlobalInput GI = new GlobalInput();
    GI = (GlobalInput) session.getValue("GI");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("var tDealNo = '");
      out.print(tDealNo);
      out.write("';\r\n");
      out.write("var tDataState = '");
      out.print(tDataState);
      out.write("';\r\n");
      out.write("var toper = '");
      out.print(toper);
      out.write("';\r\n");
      out.write("var tMngCom = '");
      out.print(GI.ComCode);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("function initForm()\r\n");
      out.write("{\r\n");
      out.write("  try\r\n");
      out.write("  {\r\n");
      out.write("  \t  initInpBox();\r\n");
      out.write("  \t  initStockBox();\r\n");
      out.write("  \t  initDetailBox(tDealNo);\r\n");
      out.write("  \t  initContBox(tDealNo);\r\n");
      out.write("  \t  fm.all(\"DealNo\").value = tDealNo;\r\n");
      out.write("  \t  fm.all(\"DataState\").value = tDataState;\r\n");
      out.write("  \t  if(fm.all(\"DealDate\").value == null || fm.all(\"DealDate\").value == \"\"){\r\n");
      out.write("  \t     fm.all(\"DealDate\").value = '");
      out.print(currentDate);
      out.write("';\r\n");
      out.write("  \t  }\r\n");
      out.write("  \t  if(fm.all(\"DealTime\").value == null || fm.all(\"DealTime\").value == \"\"){\r\n");
      out.write("  \t  fm.all(\"DealTime\").value = '");
      out.print(currentTime);
      out.write("';\r\n");
      out.write("  \t  }\r\n");
      out.write("  }\r\n");
      out.write("  catch(re)\r\n");
      out.write("  {\r\n");
      out.write("    alert(\"在LXISTradeManualDetailInput.jsp-->InitForm函数中发生异常:初始化界面错误!\");\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//查询客户信息\r\n");
      out.write("function initInpBox(){\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\t\t//客户号, 客户名称, 投保人类型\r\n");
      out.write("\t\t\tvar strSQL = \"select CSNM, CTNM, CTTP, \"\r\n");
      out.write("\t\t\t\t+ \" (select codename from ldcode b where a.CTTP = b.code and b.codetype = 'amlpolicyholdertype'), \"\r\n");
      out.write("\t\t\t\t//客户身份证件类型, 客户证件号码, 客户联系电话\r\n");
      out.write("\t\t\t\t+ \" CITP, (select codename from ldcode b where a.CITP = b.code and b.codetype = 'amlidtype'), CTID, CCTL, \"\r\n");
      out.write("\t\t\t\t//交易发生地\r\n");
      out.write("\t\t\t\t+ \" TRCD, (select codename from ldcode b where substr(a.TRCD, 0, 3) = b.code and b.codetype = 'amlcountry') || \"\r\n");
      out.write("\t\t\t\t+ \" (select codename from ldcode b where substr(a.TRCD, 4) = b.code and b.codetype = 'amlmanagecom'), \"\r\n");
      out.write("\t\t\t\t//客户职业或行业\r\n");
      out.write("\t\t\t\t+ \" CTVC, (select codename from ldcode b where a.CTVC = b.code and b.codetype = 'amloccupationtype'), \"\r\n");
      out.write("\t\t\t\t//, 代表人姓名, 代表人身份证类型, 代表人身份证件号码\r\n");
      out.write("\t\t\t\t+ \" CRNM, CRIT, (select codename from ldcode b where a.CRIT = b.code and b.codetype = 'amlidtype'), CRID, \"\r\n");
      out.write("\t\t\t\t//客户详细地址, 客户其他信息\r\n");
      out.write("\t\t\t\t+ \" CTAR, CCEI, \"\r\n");
      out.write("\t\t\t\t//可疑交易特征，可疑程度\r\n");
      out.write("\t\t\t\t+ \" STCR, SDGR, (select codename from ldcode b where a.SDGR = b.code and b.codetype = 'amlshadiness'), \"\r\n");
      out.write("\t\t\t\t//采取措施， 可疑行为描述\r\n");
      out.write("\t\t\t\t+ \" TKMS, SSDS, \"\r\n");
      out.write("\t\t\t\t// 填报人, 可疑交易生成日期, 可疑交易生成时间 \r\n");
      out.write("\t\t\t\t+ \" RPNM, DealDate, DealTime \"\r\n");
      out.write("\t\t\t\t+ \" from LXISTradeMain a where a.DealNo = '\" + tDealNo \r\n");
      out.write("\t\t\t\t+ \"' and (a.DataState = '\" + tDataState + \"' or trim(a.DataState) is null ) \"  ;\r\n");
      out.write("\t\t\tvar strQueryResult  = easyQueryVer3(strSQL, 1, 0, 1);\r\n");
      out.write("\t\t\t//判断是否查询成功\r\n");
      out.write("\t\t\tif (!strQueryResult) {\r\n");
      out.write("\t\t\t\tif(fm.all(\"TRCD\").value==null||fm.all(\"TRCD\").value=='')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t  if(tMngCom.length>=3)\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t    tMngCom = tMngCom.substring(0,3);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  var tSQL = \" SELECT concat('CHN',CODE),codename FROM LDCODE  WHERE COMCODE= '\"+tMngCom+\"' \"\r\n");
      out.write("\t\t\t\t           + \" and codetype = 'regcode' \";\r\n");
      out.write("\t\t\t\t  var arr=easyExecSql(tSQL); \r\n");
      out.write("\t\t\t\t          \r\n");
      out.write("\t\t\t\t  if(arr!=null && arr[0][0]!=null)\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t    fm.all(\"TRCD\").value=arr[0][0];\r\n");
      out.write("\t\t\t\t    fm.all(\"TRCDName\").value=arr[0][1];\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t//查询成功则拆分字符串，返回二维数组\r\n");
      out.write("\t\t\t\tvar arrSelected = decodeEasyQueryResult(strQueryResult);\r\n");
      out.write("\t\t\t\tfm.all(\"CSNM\").value   = arrSelected[0][0];\r\n");
      out.write("\t\t\t\tfm.all(\"CTNM\").value = arrSelected[0][1];\r\n");
      out.write("\t\t\t\tfm.all(\"CTTP\").value = arrSelected[0][2];\r\n");
      out.write("\t\t\t\tfm.all(\"CTTPName\").value = arrSelected[0][3];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfm.all(\"CITP\").value = arrSelected[0][4];\r\n");
      out.write("\t\t\t\tfm.all(\"CITPName\").value = arrSelected[0][5];\r\n");
      out.write("\t\t\t\tfm.all(\"CTID\").value = arrSelected[0][6];\r\n");
      out.write("\t\t\t\tfm.all(\"CCTL\").value =  arrSelected[0][7];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfm.all(\"TRCD\").value = arrSelected[0][8];\r\n");
      out.write("\t\t\t\tfm.all(\"TRCDName\").value = arrSelected[0][9];\r\n");
      out.write("\t\t\t\tfm.all(\"CTVC\").value = arrSelected[0][10];\r\n");
      out.write("\t\t\t\tfm.all(\"CTVCName\").value = arrSelected[0][11];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfm.all(\"CRNM\").value = arrSelected[0][12];\r\n");
      out.write("\t\t\t\tfm.all(\"CRIT\").value = arrSelected[0][13];\r\n");
      out.write("\t\t\t\tfm.all(\"CRITName\").value = arrSelected[0][14];\r\n");
      out.write("\t\t\t\tfm.all(\"CRID\").value = arrSelected[0][15];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfm.all(\"CTAR\").value = arrSelected[0][16];\r\n");
      out.write("\t\t\t\tfm.all(\"CCEI\").value = arrSelected[0][17];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//可疑信息\r\n");
      out.write("\t\t\t\tfm.all(\"STCR\").value = arrSelected[0][18];\r\n");
      out.write("\t\t\t\tfm.all(\"SDGR\").value = arrSelected[0][19];\r\n");
      out.write("\t\t\t\tfm.all(\"SDGRName\").value = arrSelected[0][20];\r\n");
      out.write("\t\t\t\tfm.all(\"TKMS\").value = arrSelected[0][21].replace(/@Enter/g,\"\");\r\n");
      out.write("\t\t\t\tfm.all(\"SSDS\").value = arrSelected[0][22].replace(/@Enter/g,\"\");\r\n");
      out.write("\t\t\t\tfm.all(\"RPNM\").value = arrSelected[0][23];\r\n");
      out.write("\t\t\t\tfm.all(\"DealDate\").value = arrSelected[0][24];\r\n");
      out.write("\t\t\t\tfm.all(\"DealTime\").value = arrSelected[0][25];\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}catch(ex){\r\n");
      out.write("\t\talert(\"初始化信息出错：\" + ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//初始化股东信息\r\n");
      out.write("function initStockBox(){\r\n");
      out.write("\ttry{\r\n");
      out.write("\tinitStockGrid();\r\n");
      out.write("\t//股东姓名, 股东证件类型, 股东证件号码, 股东职业或行业, 股东持股比例, 股东其他信息\r\n");
      out.write("\tvar strSQL = \"select HDNM, HITP, HDID, HDVC, HDRT, HEIF \"\r\n");
      out.write("\t\t+ \" from LXISTradeCusPartner where DealNo = '\" + tDealNo + \"' \" ;\r\n");
      out.write("\tturnPage1.queryModal(strSQL, StockGrid);\r\n");
      out.write("\t}catch(ex){\r\n");
      out.write("\t\talert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("// 初始化客户股东信息\r\n");
      out.write("function initStockGrid()\r\n");
      out.write("{                               \r\n");
      out.write("\tvar iArray = new Array();      \r\n");
      out.write("    try\r\n");
      out.write("    {\r\n");
      out.write("\t\tiArray[0]=new Array();\r\n");
      out.write("\t\tiArray[0][0]=\"序号\";   \t\t\t//列名（此列为顺序号，列名无意义，而且不显示）\r\n");
      out.write("\t\tiArray[0][1]=\"30px\"; \t     \t\t//列宽\r\n");
      out.write("\t\tiArray[0][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[0][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[1]=new Array();\r\n");
      out.write("\t\tiArray[1][0]=\"股东姓名/名称\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[1][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[1][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[1][3]=1; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[2]=new Array();\r\n");
      out.write("\t\tiArray[2][0]=\"股东证件类型\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[2][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[2][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[2][3]=2; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\t\tiArray[2][4]=\"amlidtype\"; //\r\n");
      out.write("    iArray[2][9]=\"股东证件类型|Code:amlidtype\";\r\n");
      out.write("    \r\n");
      out.write("\t\tiArray[3]=new Array();\r\n");
      out.write("\t\tiArray[3][0]=\"股东证件号码\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[3][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[3][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[3][3]=1; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[4]=new Array();\r\n");
      out.write("\t\tiArray[4][0]=\"股东职业或行业\";   \t\t  //列名\r\n");
      out.write("\t\tiArray[4][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[4][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[4][3]=2;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\tiArray[4][4]=\"amloccupationtype\";  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("    \tiArray[4][9]=\"股东职业或行业|Code:amloccupationtype\";\r\n");
      out.write("    \r\n");
      out.write("\t\tiArray[5]=new Array();\r\n");
      out.write("\t\tiArray[5][0]=\"股东持股比例(%)\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[5][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[5][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[5][3]=1;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\tiArray[6]=new Array();\r\n");
      out.write("\t\tiArray[6][0]=\"股东其他信息\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[6][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[6][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[6][3]=1;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tStockGrid = new MulLineEnter( \"fm\" , \"StockGrid\" ); \r\n");
      out.write("\t\t//这些属性必须在loadMulLine前\r\n");
      out.write("\t    StockGrid.mulLineCount = 0;   \r\n");
      out.write("\t    StockGrid.displayTitle = 1;\r\n");
      out.write("\t    StockGrid.loadMulLine(iArray); \r\n");
      out.write("\t}\r\n");
      out.write("\tcatch(ex)\r\n");
      out.write("\t{\r\n");
      out.write("\t  alert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//初始化可疑交易明细信息\r\n");
      out.write("function initDetailBox(str){\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tinitDetailGrid();\r\n");
      out.write("\t\tvar strSQL = \"select DealNo, ListNo, CSNM, TICD, TSTM,(select b.codename from ldcode b where TSTP = b.code and b.codetype='amltranstype'), (select b.codename from ldcode b where CRTP = b.code and b.codetype = 'amlcurrencytype'), \"\r\n");
      out.write("\t\t\t+ \" CRAT, (select b.codename from ldcode b where CRDR = b.code and b.codetype='amloutpaytype'), TBNM from LXISTradeDetail \"\r\n");
      out.write("\t\t\t+ \" where DealNo = '\" + str + \"' \" ;\r\n");
      out.write("\t\tturnPage2.queryModal(strSQL, DetailGrid);\r\n");
      out.write("\t}catch(ex){\r\n");
      out.write("\t\talert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function initDetailGrid(){\r\n");
      out.write("\tvar iArray = new Array();      \r\n");
      out.write("    try\r\n");
      out.write("    {\r\n");
      out.write("\t\tiArray[0]=new Array();\r\n");
      out.write("\t\tiArray[0][0]=\"序号\";   \t\t\t//列名（此列为顺序号，列名无意义，而且不显示）\r\n");
      out.write("\t\tiArray[0][1]=\"30px\"; \t     \t\t//列宽\r\n");
      out.write("\t\tiArray[0][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[0][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[1]=new Array();\r\n");
      out.write("\t\tiArray[1][0]=\"交易编号\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[1][1]=\"120px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[1][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[1][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[2]=new Array();\r\n");
      out.write("\t\tiArray[2][0]=\"明细编码\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[2][1]=\"50px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[2][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[2][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[3]=new Array();\r\n");
      out.write("\t\tiArray[3][0]=\"保险合同号\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[3][1]=\"90px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[3][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[3][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[4]=new Array();\r\n");
      out.write("\t\tiArray[4][0]=\"业务标示号\";   \t\t  //列名\r\n");
      out.write("\t\tiArray[4][1]=\"0px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[4][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[4][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[5]=new Array();\r\n");
      out.write("\t\tiArray[5][0]=\"交易日期\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[5][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[5][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[5][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\tiArray[6]=new Array();\r\n");
      out.write("\t\tiArray[6][0]=\"交易类型\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[6][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[6][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[6][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[7]=new Array();\r\n");
      out.write("\t\tiArray[7][0]=\"币种\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[7][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[7][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[7][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[8]=new Array();\r\n");
      out.write("\t\tiArray[8][0]=\"交易金额\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[8][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[8][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[8][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[9]=new Array();\r\n");
      out.write("\t\tiArray[9][0]=\"资金进出方向\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[9][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[9][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[9][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[10]=new Array();\r\n");
      out.write("\t\tiArray[10][0]=\"经办人姓名\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[10][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[10][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[10][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tDetailGrid = new MulLineEnter( \"fm\" , \"DetailGrid\" ); \r\n");
      out.write("\t\t//这些属性必须在loadMulLine前\r\n");
      out.write("\t    DetailGrid.mulLineCount = 0;   \r\n");
      out.write("\t    DetailGrid.displayTitle = 1;\r\n");
      out.write("\t\tDetailGrid.locked = 1;\t    \r\n");
      out.write("\t    DetailGrid.hiddenPlus = 1;\r\n");
      out.write("\t    DetailGrid.hiddenSubtraction = 1;     \r\n");
      out.write("\t\tDetailGrid.canSel = 1;\r\n");
      out.write("\t    DetailGrid.loadMulLine(iArray); \r\n");
      out.write("\t}\r\n");
      out.write("\tcatch(ex)\r\n");
      out.write("\t{\r\n");
      out.write("\t  alert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//初始化可疑交易保单信息\r\n");
      out.write("function initContBox(str){\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tinitContGrid();\r\n");
      out.write("\t\tvar strSQL = \"select CSNM, (select b.codename from ldcode b where ISTP = b.code and b.codetype='amlrisktype'), ISNM, RiskCode, ISPS, ITNM, ISOG, ISAT, ISFE, (select b.codename from ldcode b where ISPT = b.code and b.codetype='amlpayintv'), CTES from LXISTradeCont \"\r\n");
      out.write("\t\t\t+ \" where DealNo = '\" + str + \"' \" ;\r\n");
      out.write("\t\tturnPage3.queryModal(strSQL, ContGrid);\r\n");
      out.write("\t}catch(ex){\r\n");
      out.write("\t\talert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function initContGrid(){\r\n");
      out.write("\tvar iArray = new Array();      \r\n");
      out.write("    try\r\n");
      out.write("    {\r\n");
      out.write("\t\tiArray[0]=new Array();\r\n");
      out.write("\t\tiArray[0][0]=\"序号\";   \t\t\t//列名（此列为顺序号，列名无意义，而且不显示）\r\n");
      out.write("\t\tiArray[0][1]=\"30px\"; \t     \t\t//列宽\r\n");
      out.write("\t\tiArray[0][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[0][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[1]=new Array();\r\n");
      out.write("\t\tiArray[1][0]=\"保险合同号\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[1][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[1][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[1][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[2]=new Array();\r\n");
      out.write("\t\tiArray[2][0]=\"保险种类\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[2][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[2][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[2][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[3]=new Array();\r\n");
      out.write("\t\tiArray[3][0]=\"保险名称\";    \t\t  //列名\r\n");
      out.write("\t\tiArray[3][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[3][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[3][3]=0; //是否允许输入,1表示允许，0表示不允许,2表示代码选择，3表示该列是隐藏的\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[4]=new Array();\r\n");
      out.write("\t\tiArray[4][0]=\"保险编码\";   \t\t  //列名\r\n");
      out.write("\t\tiArray[4][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[4][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[4][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[5]=new Array();\r\n");
      out.write("\t\tiArray[5][0]=\"保险期间\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[5][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[5][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[5][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\tiArray[6]=new Array();\r\n");
      out.write("\t\tiArray[6][0]=\"被保险人总数\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[6][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[6][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[6][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[7]=new Array();\r\n");
      out.write("\t\tiArray[7][0]=\"保险标的\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[7][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[7][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[7][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[8]=new Array();\r\n");
      out.write("\t\tiArray[8][0]=\"保险金额\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[8][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[8][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[8][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[9]=new Array();\r\n");
      out.write("\t\tiArray[9][0]=\"保险费\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[9][1]=\"60px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[9][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[9][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\r\n");
      out.write("\t\tiArray[10]=new Array();\r\n");
      out.write("\t\tiArray[10][0]=\"缴费方式\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[10][1]=\"80px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[10][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[10][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tiArray[11]=new Array();\r\n");
      out.write("\t\tiArray[11][0]=\"保险合同其他信息\";\t   \t\t//列名\r\n");
      out.write("\t\tiArray[11][1]=\"0px\";\t\t\t//列宽\r\n");
      out.write("\t\tiArray[11][2]=100;\t\t\t//列最大值\r\n");
      out.write("\t\tiArray[11][3]=0;  \t\t\t//是否允许输入,1表示允许，0表示不允许\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tContGrid = new MulLineEnter( \"fm\" , \"ContGrid\" ); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//这些属性必须在loadMulLine前\r\n");
      out.write("\t    ContGrid.mulLineCount = 0;   \r\n");
      out.write("\t    ContGrid.displayTitle = 1;\r\n");
      out.write("\t\tContGrid.locked = 1;\t    \r\n");
      out.write("\t    ContGrid.hiddenPlus = 1;\r\n");
      out.write("\t    ContGrid.hiddenSubtraction = 1;     \r\n");
      out.write("\t\tContGrid.canSel = 1;\r\n");
      out.write("\t    ContGrid.loadMulLine(iArray); \r\n");
      out.write("\t}\r\n");
      out.write("\tcatch(ex)\r\n");
      out.write("\t{\r\n");
      out.write("\t  alert(ex);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onload=\"initForm(); initElementtype();\">\n");
      out.write("\t<form action=\"./LXISTradeManualDetailSave.jsp\" method=post name=\"fm\" target=\"fraSubmit\" >\t\t\n");
      out.write("<!--\n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("                      引入客户基本信息录入控件         \n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("-->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "ISTradeCustomerPage.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("                      客户股东信息控件         \n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("-->\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td class=common>\n");
      out.write("\t\t\t<IMG  src= \"../common/images/butExpand.gif\" style= \"cursor:hand;\" OnClick= \"showPage(this,divStock);\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td class= titleImg>\n");
      out.write("\t\t\t\t客户股东信息\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t<Div  id= \"divStock\" style= \"display: '' \"/>\n");
      out.write("\t\t<table  class= common>\n");
      out.write("\t\t\t<tr  class= common>\n");
      out.write("\t\t\t\t<td text-align: left colSpan=1>\n");
      out.write("\t\t\t\t<span id=\"spanStockGrid\" >\n");
      out.write("\t\t\t\t</span> \n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</Div>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("                      可疑交易信息控件         \n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("-->\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td class=common>\n");
      out.write("\t\t\t<IMG  src= \"../common/images/butExpand.gif\" style= \"cursor:hand;\" OnClick= \"showPage(this,divTrans);\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td class= titleImg>\n");
      out.write("\t\t\t\t可疑交易信息\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("\t<Div id= \"divTrans\" style= \"display: '' \">\n");
      out.write("\t\t<table class=common border=0>\n");
      out.write("\t\t\t<TR class=common>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 可疑交易特征</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\" />\n");
      out.write("\t\t\t        <Input name=\"STCR\" id=\"STCR\" class=\"code\" verify = \"可疑交易特征|notnull&Code:amlshadinessstamp\" \n");
      out.write("\t      \t\t\t\t\tondblclick=\"showCodeList('amlshadinessstamp',[this]);\" \t\n");
      out.write("\t      \t\t\t\t\tonkeyup=\"showCodeListKey('amlshadinessstamp',[this]);\"\n");
      out.write("\t    \t\t\t\t\t elementtype=nacessary/>\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 可疑程度</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\"/>\n");
      out.write("\t\t\t        <Input name=\"SDGR\" id=\"SDGR\" class=\"codeno\"\tverify = \"可疑程度|notnull&Code:amlshadiness\"\n");
      out.write("\t      \t\t\t\t\tondblclick=\"showCodeList('amlshadiness',[this,SDGRName],[0,1]);\" \t\n");
      out.write("\t      \t\t\t\t\tonkeyup=\"showCodeListKey('amlshadiness',[this,SDGRName],[0,1]);\"\n");
      out.write("\t    \t\t\t\t\t/><Input class=codename name=SDGRName readOnly elementtype=nacessary />\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 填报人</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\"/>\n");
      out.write("\t\t\t        <Input name=\"RPNM\" id=\"RPNM\" class=\"common\" value=\"");
      out.print(tGI.Operator);
      out.write("\" \n");
      out.write("\t\t\t\t\t\tverify = \"填报人|notnull&len<=20\" elementtype=nacessary />\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t</TR>\n");
      out.write("\t\t\t<TR class=common>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 可疑交易生成日期</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\"/>\n");
      out.write("\t\t\t        <Input name=\"DealDate\" id=\"DealDate\" class='coolDatePicker' \n");
      out.write("\t\t\t\t\t\tverify = \"可疑交易生成日期|date&notnull\" elementtype=nacessary />\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 可疑交易生成时间</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\"/>\n");
      out.write("\t\t\t        <Input name=\"DealTime\" id=\"DealTime\" class=\"common\" \n");
      out.write("\t\t\t\t\t\tverify = \"可疑交易生成时间|notnull\"  elementtype=nacessary/>\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> </TD>\n");
      out.write("\t\t\t\t<TD class=\"input\"/> </TD>\n");
      out.write("\t\t\t</TR>\n");
      out.write("\t\t\t<TR class=common>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 采取措施</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\" colspan=5  />\n");
      out.write("\t\t\t        <textarea style=\"width:97%\"  name=\"TKMS\" id=\"TKMS\" class=\"common\" \n");
      out.write("\t\t\t\t\t\tverify = \"采取措施|notnull&len<=128\" elementtype=nacessary/></textarea>\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t</TR>\n");
      out.write("\t\t\t<TR class=common>\n");
      out.write("\t\t\t\t<TD class=\"title\" /> 可疑行为描述</TD>\n");
      out.write("\t\t\t\t<TD class=\"input\" colspan=5  />\n");
      out.write("\t\t\t        <textarea style=\"width:97%\"  name=\"SSDS\" id=\"SSDS\" class=\"common\" \n");
      out.write("\t\t\t\t\t\tverify = \"可疑行为描述|notnull&len<=500\" elementtype=nacessary/></textarea>\n");
      out.write("\t\t        </TD>\n");
      out.write("\t\t\t</TR>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t<input type=\"hidden\" name=\"hideOperate\" id=\"hideOperate\" value=\"\" />\n");
      out.write("\t<input type=\"hidden\" name=\"DealNo\" id=\"DealNo\" value=\"\" />\n");
      out.write("\t<input type=\"hidden\" name=\"DataState\" id=\"DataState\" value=\"\" />\n");
      out.write("\t<INPUT class=cssButton VALUE=\" 保存 \" name=\"insert\" TYPE=button onclick=\"return GoToInputMain();\" />\t\n");
      out.write("\t<hr>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("                      可疑交易明细信息控件         \n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("-->\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td class=common>\n");
      out.write("\t\t\t<IMG  src= \"../common/images/butExpand.gif\" style= \"cursor:hand;\" OnClick= \"showPage(this,divDetail);\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td class= titleImg>\n");
      out.write("\t\t\t\t可疑交易明细信息\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t<Div  id= \"divDetail\" style= \"display: '' \"/>\n");
      out.write("\t\t<table  class= common>\n");
      out.write("\t\t\t<tr  class= common>\n");
      out.write("\t\t\t\t<td text-align: left colSpan=1>\n");
      out.write("\t\t\t\t<span id=\"spanDetailGrid\" >\n");
      out.write("\t\t\t\t</span> \n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<table align=\"center\">\n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"首页\" TYPE=button onclick=\"turnPage2.firstPage();\" /> \n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"上一页\" TYPE=button onclick=\"turnPage2.previousPage();\" />\n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"下一页\" TYPE=button onclick=\"turnPage2.nextPage();\" /> \n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"尾页\" TYPE=button onclick=\"turnPage2.lastPage();\" />\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 新增 \" name=\"insert\" TYPE=button onclick=\"return GoToDetailInput(this.name);\" />\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 修改 \" name=\"update\" TYPE=button onclick=\"return GoToDetailInput(this.name);\" />\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 删除 \" name=\"delete\" TYPE=button onclick=\"return GoToDetailInput(this.name);\" />\t\t\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 查看 \" name=\"newquery\" TYPE=button onclick=\"return GoToDetailInput(this.name);\" />\t\t\n");
      out.write("\t</Div>\n");
      out.write("\t<hr>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("                      可疑交易合同信息控件         \n");
      out.write("    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV\n");
      out.write("-->\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td class=common>\n");
      out.write("\t\t\t<IMG  src= \"../common/images/butExpand.gif\" style= \"cursor:hand;\" OnClick= \"showPage(this,divCont);\">\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td class= titleImg>\n");
      out.write("\t\t\t\t可疑交易合同明细信息\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t\t<Div  id= \"divCont\" style= \"display: '' \"/>\n");
      out.write("\t\t\t<table  class= common>\n");
      out.write("\t\t\t\t<tr  class= common>\n");
      out.write("\t\t\t\t\t<td text-align: left colSpan=1>\n");
      out.write("\t\t\t\t\t<span id=\"spanContGrid\" >\n");
      out.write("\t\t\t\t\t</span> \n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<table align=\"center\">\n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"首页\" TYPE=button onclick=\"turnPage3.firstPage();\" /> \n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"上一页\" TYPE=button onclick=\"turnPage3.previousPage();\" />\n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"下一页\" TYPE=button onclick=\"turnPage3.nextPage();\" /> \n");
      out.write("\t\t\t<INPUT CLASS=cssButton VALUE=\"尾页\" TYPE=button onclick=\"turnPage3.lastPage();\" />\n");
      out.write("\t\t  </table>\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t</Div>\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 新增 \" name=\"insert\" TYPE=button onclick=\"return GoToContInput(this.name);\" />\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 修改 \" name=\"update\" TYPE=button onclick=\"return GoToContInput(this.name);\" />\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 删除 \" name=\"delete\" TYPE=button onclick=\"return GoToContInput(this.name);\" />\t\t\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 查看 \" name=\"newquery\" TYPE=button onclick=\"return GoToContInput(this.name);\" />\t\t\t\t\n");
      out.write("\t\t<INPUT class=cssButton VALUE=\" 返回 \" name=\"return\" TYPE=button onclick=\"return GoToReturn();\" />\t\t\t\t\t\t\n");
      out.write("\t</form>\t\n");
      out.write("<span id=\"spanCode\" style=\"display: none; position:absolute; slategray\"></span>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("if (toper == \"query\"){\n");
      out.write("\tfor (var elementsNum=0; elementsNum< document.forms[0].elements.length; elementsNum++)\n");
      out.write("\t{\n");
      out.write("\t\tvar element = document.forms[0].elements[elementsNum];\n");
      out.write("\t\telement.readOnly = true;\n");
      out.write("\t\tif (element.name == \"insert\" || element.name == \"update\" || element.name == \"delete\" )\n");
      out.write("\t\t\t//element.style.visibility = \"hidden\";\n");
      out.write("\t\t\telement.disabled = true;\n");
      out.write("\t}\t\t\n");
      out.write("}\n");
      out.write("\t\t\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
